# Generated by Django 4.2.7 on 2023-12-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_alter_comment_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=700),
        ),
    ]
