# Generated by Django 4.2.7 on 2023-12-06 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post_liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reg.post'),
        ),
    ]
