# Generated by Django 4.2.7 on 2023-11-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0006_alter_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='like_author',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='post_liked',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post_liked', 'like_author')},
        ),
    ]
