# Generated by Django 4.2.7 on 2023-11-21 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_rename_user_like_like_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reg.post'),
        ),
    ]
